name: Deploy UI to AWS
on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  deploy-ui:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    env:
      CODE_BUCKET: ${{vars.CODE_BUCKET}}
      AWS_REGION: ${{ vars.AWS_REGION }}
      VITE_GOOGLE_MAPS_API_KEY: ${{ vars.VITE_GOOGLE_MAPS_API_KEY }}
      VITE_API_SERVER_URL: ${{ vars.VITE_API_SERVER_URL }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache ui files
        id: cache-ui
        uses: actions/cache@v4
        env: 
          cache-name: cache-ui-files
        with:
          path: .
          key: ${{ hashFiles('package*.json') }}-${{ hashFiles('src/**/*') }}

      - if: ${{ steps.cache-ui.outputs.cache-hit == 'true' }}
        name: Check ui changes
        continue-on-error: true
        run: echo 'No ui changes found. Skip ui build and deployment.'

      - if: ${{ steps.cache-ui.outputs.cache-hit != 'true' }}
        name: Build 
        run: |
          export VITE_GOOGLE_MAPS_API_KEY="${{ vars.VITE_GOOGLE_MAPS_API_KEY }}"
          export VITE_API_SERVER_URL="${{ vars.VITE_API_SERVER_URL }}"
          npm ci
          npm run build

      - if: ${{ steps.cache-ui.outputs.cache-hit != 'true' }}
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}

      - if: ${{ steps.cache-ui.outputs.cache-hit != 'true' }}
        name: Sync with S3
        run: |
          aws s3 sync ./dist s3://$CODE_BUCKET --delete

      - if: ${{ steps.cache-ui.outputs.cache-hit != 'true' }}
        name: Invalidate cloudfront
        run: |
          # Send SSM command to invalidate cloudfront
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
